apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongoosepush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpush
  template:
    metadata:
      labels:
        app: mpush
    spec:
      containers:
      - name: mpush
        image: {{ .Values.image.repository }}:{{or .Values.image.tag .Chart.AppVersion}}
        imagePullPolicy: IfNotPresent
        env:
        - name: PUSH_APNS_ENABLED
          value: "false"
        - name: PUSH_HTTPS_CERTFILE
          value: /opt/app/priv/ssl/rest_cert.pem
        - name: PUSH_HTTPS_KEYFILE
          value: /opt/app/priv/ssl/rest_key.pem
        volumeMounts:
        - name: config-map
          mountPath: /opt/app/priv/fcm
        - name: secret
          readOnly: true
          mountPath: /opt/app/priv/ssl
      volumes:
      - name: config-map
        configMap:
          name: mongoosepush-cm
      - name: secret
        secret:
          secretName: mongoosepush-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mongoosepush
spec:
  clusterIP: None
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    app: mpush
