apiVersion: v1
kind: Service
metadata:
  name: mongoose
  labels:
    app: mongoose
spec:
  ports:
  - name: epmd
    port: 4369
    targetPort: 4369
  - name: c2s
    port: 5222
    targetPort: 5222
  - name: s2s
    port: 5269
    targetPort: 5269
  - name: bosh
    port: 5280
    targetPort: 5280
  - name: erlang-dist
    targetPort: 9100
    port: 9100
  clusterIP: None
  selector:
    app: mongoose
