apiVersion: v1
kind: ConfigMap
metadata:
  name: mongooseim
  labels:
    app: mongooseim
data:
  {{- $root := . }}
  {{- range tuple "vm.args" "mongooseim.toml" }}
  {{ . }}: |-
    {{- tpl ($root.Files.Get .) $root | nindent 4}}
  {{- end }}
