apiVersion: v1
kind: ConfigMap
metadata:
  name: mongooseim
  labels:
    app: mongooseim
data:
  mongooseim.toml: |-
      {{- tpl (.Files.Get "configs/mongooseim.toml") . | nindent 4 }}
  vm.args: |-
      {{- tpl (.Files.Get "configs/vm.args") . | nindent 4 }}
