apiVersion: v1
kind: ConfigMap
metadata:
  name: mongooseim
  labels:
    app: mongooseim
data:
  app.config: |-
    {{- if .Values.appConfig }}
      {{- printf "%s" (tpl .Values.appConfig $) | nindent 4 }}
    {{- else }}
      {{- tpl (.Files.Get "configs/app.config") . | nindent 4 }}
    {{- end }}
  mongooseim.toml: |-
    {{- if .Values.mimConfig }}
      {{- printf "%s" (tpl .Values.mimConfig $) | nindent 4 }}
    {{- else }}
      {{- tpl (.Files.Get "configs/mongooseim.toml") . | nindent 4 }}
    {{- end }}
  vm.args: |-
    {{- if .Values.vmConfig }}
      {{- printf "%s" (tpl .Values.vmConfig $) | nindent 4 }}
    {{- else }}
      {{- tpl (.Files.Get "configs/vm.args") . | nindent 4 }}
    {{- end }}
  {{- $files := .Files }}
  {{- range $key, $value := .Files }}
  {{- if hasPrefix "artifacts/" $key }} {{/* only when in config-dir/ */}}
  {{ $key | trimPrefix "artifacts/" }}: {{ $files.Get $key | quote }} {{/* adapt $key as desired */}}
  {{- end }}
  {{- end }}
