{{ if .Values.nodeport.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongooseim-nodeport
  namespace:
  labels:
spec:
  ports:
  - protocol: TCP
    port: 5222
    targetPort: 5222
  - protocol: TCP
    port: 5223
    targetPort: 5223
  selector:
    app: mongooseim
  type: NodePort
{{ end }}
