apiVersion: v1
kind: Service
metadata:
  name: mongooseim-lb
  namespace:
  labels:
spec:
  ports:
  - name: c2s
    protocol: TCP
    port: 5222
    targetPort: 5222
  - name: gql-dom-admin
    protocol: TCP
    port: 5541
    targetPort: 5541
  - name: gql-user
    protocol: TCP
    port: 5561
    targetPort: 5561
  selector:
    app: mongooseim
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
