apiVersion: v1
kind: Service
metadata:
  name: mongooseim-lb
  namespace:
  labels:
spec:
  ports:
  - protocol: TCP
    port: 5222
    targetPort: 5222
  selector:
    app: mongooseim
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
