apiVersion: v1
kind: ConfigMap
metadata:
  name: mongooseim
  labels:
    app: mongooseim
data:
  vm.args: |
    ## Name of the node.
    -name mongooseim

    ## Cookie for distributed erlang
    -setcookie ejabberd

    ## Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
    ## (Disabled by default..use with caution!)
    ##-heart

    ## Enable kernel poll and a few async threads
    +K true
    +A 5
    +P 10000000

    ## Increase number of concurrent ports/sockets
    -env ERL_MAX_PORTS 250000

    ## Tweak GC to run more often
    -env ERL_FULLSWEEP_AFTER 2

    ## With lager sasl reports are redundant so turn them off
    -sasl sasl_error_logger false

    -kernel inet_dist_listen_min 9100
    -kernel inet_dist_listen_max 9100
