apiVersion: v1
kind: Service
metadata:
  name: mongooseim
  labels:
    app: mongooseim
spec:
  ports:
  - name: epmd
    port: 4369
    targetPort: 4369
  - name: c2s
    port: 5222
    targetPort: 5222
  - name: s2s
    port: 5269
    targetPort: 5269
  - name: bosh-ws
    port: 5280
    targetPort: 5280
  - name: bosh-wss
    port: 5285
    targetPort: 5285
  - name: erlang-dist
    port: 9100
    targetPort: 9100
  - name: gql-admin
    port: 5551
    targetPort: 5551
  - name: gql-dom-admin
    port: 5541
    targetPort: 5541
  - name: gql-user
    port: 5561
    targetPort: 5561
  # Headless service
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: mongooseim
